import "./globals.css";
import Styles from "./layout.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Final mission",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ backgroundColor: "#A6D5FF", margin: "0px" }}
      >
        <header>
          <h1 className={Styles.mainTitle}>Hello World!</h1>
        </header>
        <div style={{ margin: "10vh 0 0 0" }}>{children}</div>
      </body>
    </html>
  );
}
